apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
jobs:
  build:
    steps: # comment update Nov 6 - 4
      - uses: docker://alpine:latest
        run: |
          apk update && apk add git python3 && git config --global --add safe.directory /cloudbees/workspace
      - name: checkout
        uses: https://github.com/cloudbees-io/checkout@v1
      - name: Build app
        uses: docker://golang:1.24
        run: |
          go build -v ./...
      - name: Setup GH registry
        uses: https://github.com/cloudbees-io/configure-oci-credentials@v1
        with:
          registry: ghcr.io
          username: ${{ vars.GH_USERNAME }}
          password: ${{ secrets.GH_TOKEN_PACKAGE_ADMIN }}
      - name: Publish container
        uses: https://github.com/cloudbees-io/kaniko@v1
        with:
          destination: ghcr.io/status-optics/runner:${{ cloudbees.version}}
